export interface MusicalParams {
  scale: 'major' | 'minor' | 'pentatonic' | 'chromatic' | 'wholeTone';
  baseFrequency: number; // Hz
  tempo: number; // BPM
  complexity: number; // 0-1
  mood: 'melancholic' | 'uplifting' | 'ethereal' | 'mysterious';
}

export interface Memory {
  id: string;
  imageUrl: string; // The photo
  diary: string;
  date: string; // Formatted date string
  keywords: string[]; // Generated by AI
  musicalParams: MusicalParams; // Generated by AI
  title: string;
}

export interface HandState {
  isDetected: boolean;
  isOpen: boolean; // All fingers spread
  isClosed: boolean; // Fist (Grab)
  isPinched: boolean; // Thumb and Index touching
  isPeaceSign: boolean; // Index and Middle finger up (Victory sign)
  pinchDistance: number; // 0.0 (touching) to 1.0 (far apart)
  position: { x: number; y: number; z: number }; // Normalized coordinates
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}